### ISSUE TITLE
Multiple nodes on single IP are not supported

### ISSUE THREAD

**Issue by brainkiller** [Scalingo/docker-munin-server#10]
Change this line in the startup script:
  if ! grep -q $HOST /etc/munin/munin.conf ; then
to
  if ! grep -q $NAME /etc/munin/munin.conf ; then

in order to support multiple nodes with the same IP.
This could be usefull for SNMP monitoring of other systems

**Comment by brainkiller** [comment]
I should have been more clear. It's in this loop that we need to change the grep:

# generate node list
for NODE in $SNMP_NODES
do
  NAME=`echo $NODE | cut -d ":" -f1`
  HOST=`echo $NODE | cut -d ":" -f2`
  PORT=`echo $NODE | cut -d ":" -f3`
  if [ ${#PORT} -eq 0 ]; then
      PORT=4949
  fi
  if ! grep -q $HOST /etc/munin/munin.conf ; then
    cat << EOF >> /etc/munin/munin.conf
[$NAME]
    address $HOST
    use_node_name no
    port $PORT

EOF
    fi
done

**Comment by EtienneM** [comment]
Closing this as the repository is moved to read only mode as it hasn't been maintained for years.
