### ISSUE TITLE
Cannot get data from node running inside server container

### ISSUE THREAD

**Issue by sandrodz** [Scalingo/docker-munin-server#11]
docker-munin-server has a munin-node running along with server inside the container.

I added localhost to docker-compose.yml file as shown in the screenshot, but I still get only: "Munin has not run yet. Please try again in a few moments." even after waiting 10 mins.

<img width="1249" alt="screen shot 2017-07-17 at 12 21 25 am" src="https://user-images.githubusercontent.com/8479569/28251029-f270d85e-6a85-11e7-9ab6-df6ab50f71c8.png">

**Comment by sandrodz** [comment]
oh actually cron is not running at all!
notice error:
```(*system*munin)` NUMBER OF HARD LINKS > 1 ```

**Comment by sandrodz** [comment]
I fixed this by running inside container:

```touch /etc/crontab /etc/cron.d/*```

**Comment by elietheocari** [comment]
This fixed it for me as well, thank you @sandrodz

**Comment by EtienneM** [comment]
Closing this as the repository is moved to read only mode as it hasn't been maintained for years.
