### ISSUE TITLE
update NODES

### ISSUE THREAD

**Issue by revolunet** [Scalingo/docker-munin-server#14]
Hi,

wondering how you would add some NODES on a an existing instance ?

Thanks

**Comment by dotmpe** [comment]
Alternatively:

- edit container munin.conf (change will be gone after restart) and restart munin-node proc; or
- stop instance and start new instance with updated NODES env

Addendum:

Editing running instance:
```
docker exec -ti <munin-server-name> bash
apt-get install vim
vim /etc/munin/munin.conf
systemctl restart munin
```

This is useful to test things only. If you look at the scripts, the setup is pretty minimal and makes for easy use and maintenance. 

If you want to go further, I suppose you can mount the munin.conf and get/build your own munin-server. I use systemd and have that write the env settings too. Here is a script to update NODES and SSH_NODES, by scanning for ZeroTier One aliases  (hostname.zt) in ``/etc/hosts``. Should work on scalingo/munin-server
```
test -n "$DCKR_VOL" || export DCKR_VOL=/srv/docker-volumes-local
test -n "$DCKR_CONF" || export DCKR_CONF=$HOME/.local/etc
{
  echo MUNIN_USERS=$(whoami)
  echo MUNIN_PASSWORDS=$(whoami)

  echo "NODES=$(echo $(
    grep '[a-z-]*\.zt' /etc/hosts | grep -vi '...' |
       sed 's/\.zt//g' |
      awk '{print ""$2":"$1":4949"}' )) ..."

  echo "SSH_NODES=...."

} > $DCKR_CONF/scalingo-munin-server.env

# Replace add_hostlist
newvalue="$(grep '[a-z-]*.zt' /etc/hosts | awk '{print "--add-host "$2":"$1}' | tr '\n' ' ' )"
sed -i 's/add_hostlist=.*/add_hostlist='"$newvalue"'/' /etc/sysconfig/box-environment
```

``$add_hostlist`` is be added to ``docker run`` to let the container know about the hosts too, and the ``*.env`` file provides munin's settings./

Run the above before the systemd unit starts, and use the global environment file
```
EnvironmentFile=/etc/sysconfig/box-environment
ExecStartPre=/bin/sh ${DCKR_CONF}/scalingo-munin-server.sh
ExecStart=/usr/bin/docker run \
  ...
  --env-file ${DCKR_CONF}/scalingo-munin-server.env \
  ...
  $add_hostlist
  ...
```

**Comment by EtienneM** [comment]
Closing this as the repository is moved to read only mode as it hasn't been maintained for years.
