### ISSUE TITLE
Add installation instruction

### ISSUE THREAD

**Issue by viktorsmari** [Scalingo/docker-munin-server#2]
Could you provide installation instruction for beginners in README.md?

For example:
What should be done after `docker build .` ?

**Comment by Soulou** [comment]
Yes of course, doing it right now

**Comment by Soulou** [comment]
Is it alright for you now: https://github.com/Scalingo/docker-munin-server/blob/master/README.md ?

**Comment by viktorsmari** [comment]
Could you add this command before you run the longer command:

`docker build -t munin-server .`

And add a "\" at the end of the second last line.

Then the image starts perfectly.

But then when I access localhost:8080 I get:

_Munin has not run yet. Please try again in a few moments._
Which I guess is a config thing?

**Comment by Soulou** [comment]
Thanks for the typo '\', the build command has been added, and a little
information about the message you're mentionning.

https://github.com/Scalingo/docker-munin-server/blob/master/README.md

Le lun. 14 déc. 2015 à 09:26, Viktor Smári notifications@github.com a
écrit :

**Comment by viktorsmari** [comment]
Perfect, fixed!
