### ISSUE TITLE
munin-cgi is not working

### ISSUE THREAD

**Issue by azimut** [Scalingo/docker-munin-server#3]
Is this only not working for me? We need something like this? `http://munin-monitoring.org/wiki/MuninConfigurationMasterCGI#CGIgraph`

Url containing the url returning 404: `http://munin.domain.com/static/dynazoom.html?cgiurl_graph=/munin-cgi/munin-cgi-graph&plugin_name=domain.com/server1.domain.com/ox_grizzly_httpCodecFilter&size_x=800&size_y=400&start_epoch=1456087819&stop_epoch=1456779019`
Url returning 404: `http://munin.domain.com/munin-cgi/munin-cgi-graph/domain.com/server1.domain.com/ox_grizzly_httpCodecFilter-pinpoint=1456087819,1456779019.png?&lower_limit=&upper_limit=&size_x=800&size_y=400`

**Comment by dfyx** [comment]
Same problem for me...

**Comment by Soulou** [comment]
Fixed by https://github.com/Scalingo/docker-munin-server/pull/7 ping @azimut  @dfyx
