### ISSUE TITLE
Volumes: Permission denied

### ISSUE THREAD

**Issue by phlegx** [Scalingo/docker-munin-server#4]
I'm mapping the volumes with `docker-compose` like so:

```
volumes:
  - /opt/dockerdata/munin/var/lib/munin:/var/lib/munin
  - /opt/dockerdata/munin/var/log/munin:/var/log/munin
  - /opt/dockerdata/munin/var/run/munin:/var/run/munin
  - /opt/dockerdata/munin/var/cache/munin:/var/cache/munin
```

However, I do get a permission denied when the Munin daemon wants to write to this directories. Does anyone else experience that? Could the image may take care of this, so that the Munin daemon can write to the directories without setting extra permissions on the host?

thanks!

**Comment by zavulon** [comment]
You can write relative paths in docker-compose.yml. If you have `/opt/dockerdata/munin/docker-compose.yml` you can refer to directories like `./var/lib/munin:/var/lib/munin`.

Docker is creating these directories if they don't exist and default permissions are for root user only. Create them manually and chown them to munin user. It is also possible to make this chown automatically in `start-munin.sh`. You can make the patch and add pull request.

**Comment by phlegx** [comment]
First of all thanks for the reply! Oh its been ah while since this was opened.  I think it is a very good idea to automatically chown it in `start-munin.sh`. I will add this later on and make a pull request.

**Comment by Soulou** [comment]
Merged :-)
