### ISSUE TITLE
spawn-fcgi not running on fresh container

### ISSUE THREAD

**Issue by srigi** [Scalingo/docker-munin-server#9]
This line of starting [`spawn-fcgi`](https://github.com/Scalingo/docker-munin-server/blob/1ed62c531f44712bc7f86ed8f8bcf1afa8d01132/start-munin.sh#L127) is not exactly very reliable. There should be some test/retry for this command. In my cast this process is constantly down after container is started.

**Comment by revolunet** [comment]
same here; did you find a solution for it ?

**Comment by EtienneM** [comment]
Closing this as the repository is moved to read only mode as it hasn't been maintained for years.
